version: '3'
services:
    web:
        image: microcoffeeoncloud-web:1.0.0-SNAPSHOT
        ports:
            - "8090:8090"
            - "8453:8453"
        depends_on:
            - location
            - order
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery
    location:
        image: microcoffeeoncloud-location:1.0.0-SNAPSHOT
        ports:
            - "8081:8081"
            - "8444:8444"
        depends_on:
            - mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery
    order:
        image: microcoffeeoncloud-order:1.0.0-SNAPSHOT
        ports:
            - "8082:8082"
            - "8445:8445"
        depends_on:
            - creditrating
            - mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery
    creditrating:
        image: microcoffeeoncloud-creditrating:1.0.0-SNAPSHOT
        ports:
            - "8083:8083"
            - "8446:8446"
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery
    mongodb:
        image: microcoffeeoncloud-database:1.0.0-SNAPSHOT
        command: mongod --sslMode preferSSL --sslPEMKeyFile /microcoffee.study-key.pem --bind_ip_all
        ports:
            - "27017:27017"
            - "28017:28017"
        domainname: microcoffee.study
        volumes:
            - mongodbdata:/data/db
        networks:
            microcoffee:
                aliases:
                    - database.microcoffee.study

volumes:
    mongodbdata:
        external: true

networks:
    microcoffee:
    configserver:
        external:
            name: microcoffeeoncloudconfigserver_configserver
    discovery:
        external:
            name: microcoffeeonclouddiscovery_discovery
